const data = [
    {
        id: 1,
        userScore: 11,
        oppScore: 9,
        dayOfWeek: 'Saturday',
        date: 'Aug 20 2022',
        time: '5:13pm',
        player1: 'dylan',
        player2: 'kass',
        player3: 'mads',
        player4: 'robert',
    },
    {
        id: 2,
        userScore: 6,
        oppScore: 11,
        dayOfWeek: 'Saturday',
        date: 'Aug 20 2022',
        time: '6:45pm',
        player1: 'dylan',
        player2: 'kass',
        player3: 'mads',
        player4: 'robert',
    },
    {
        id: 3,
        userScore: 11,
        oppScore: 9,
        dayOfWeek: 'Saturday',
        date: 'Aug 20 2022',
        time: '5:13pm',
        player1: 'dylan',
        player2: 'kass',
        player3: 'mads',
        player4: 'robert',
    },
];

export default data;
